# src/utils/BUILD
load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "logging",
    srcs = ["logging.cpp"],
    hdrs = ["logging.h"],
    visibility = ["//src:__pkg__"],  # Change this to //visibility:public if needed
)
